apiVersion: v1
kind: Secret
metadata:
  name: {{ template "postgis.fullname" . }}
  labels:
    app: postgis
    chart: {{ template "postgis.chart" . }}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
type: Opaque
data:
  postgresql-password: {{ include "postgresql.password" . | b64enc | quote }}