apiVersion: v1
kind: Service
metadata:
  name: {{ template "postgis.fullname" . }}-headless
  labels:
    app: postgis
    chart: {{ template "postgis.fullname" . }}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: tcp-postgis
      port: 5432
      targetPort: tcp-postgis
  selector:
    app: postgis
    release: {{ .Release.Name | quote }}
