{{- if or (not .Values.existingSecret) .Values.extraSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "postgis.secretName" . }}
  labels:
    app: {{ template "postgis.fullname" . }}
    chart: {{ template "postgis.chart" . }}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
type: Opaque
data:
  {{- if not .Values.existingSecret }}
  postgresql-user: {{ .Values.postgresqlUsername | b64enc | quote }}
  postgresql-password: {{ include "postgresql.password" . | b64enc | quote }}
  {{- end }}
  {{- with .Values.extraSecret }}
  {{- tpl . $ | nindent 2 }}
  {{- end }}
{{- end }}
