apiVersion: v1
kind: Service
metadata:
  name: {{ include "geoserver.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "geoserver.fullname" . }}
    chart: {{ template "geoserver.chart" . }}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
    {{- with .Values.service.labels }}
    {{- tpl . $ | nindent 4 }}
    {{- end }}
  annotations:
    {{- with .Values.service.annotations }}
    {{- tpl . $ | nindent 4 }}
    {{- end }}
spec:
  type: {{ .Values.service.type }}
  {{- if and (eq .Values.service.type "LoadBalancer") .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ default "" .Values.service.loadBalancerIP }}
  {{- end }}
  ports: 
    - port: {{ .Values.service.port }}
      targetPort: http-geoserver
      protocol: TCP
      name: http-geoserver
      {{- if eq .Values.service.type "NodePort" }}
      nodePort: {{ default "" .Values.service.nodePort}}
      {{- end }}
  {{- if .Values.service.externalIPs }}
  externalIPs: {{- toYaml .Values.service.externalIPs | nindent 4 }}
  {{- end }}
  selector:
    app: {{ template "geoserver.fullname" . }}
    release: {{ .Release.Name | quote }}
