apiVersion: v1
name: geonode
version: 0.1.1
appVersion: 3.0.0
description: Chart for GeoNode
keywords:
  - GeoNode
  - GIS
engine: gotpl
dependencies:
  - name: postgis
    version: 0.1.1
    repository: "file://../../postgis/v0.1.1"
    condition: postgis.enabled
    tags:
      - database-backend
      - postgis
  - name: geoserver
    version: 0.1.1
    repository: "file://../../geoserver/v0.1.1"
    condition: geoserver.enabled
    tags:
      - map-backend
      - geoserver
