apiVersion: v2
name: postgis
version: 0.2.1
appVersion: 12.1-3
description: Chart for postgis
keywords:
  - postgis
  - postgresql
  - database
  - postgres
  - sql
  - replication
  - cluster
home: https://postgis.net/
sources:
  - https://github.com/kartoza/docker-postgis
maintainers:
  - name: Rizky Maulana Nugraha
    email: rizky@kartoza.com
engine: gotpl
icon: https://raw.githubusercontent.com/lucernae/kartoza-rancher-charts/geonode/assets/logo/postgis.png
