apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ template "postgis.fullname" . }}
  labels:
    app: {{ template "postgis.fullname" . }}
    chart: {{ template "postgis.chart" . }}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
  {{- with .Values.labels }}
  {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.annotations }}
  annotations: {{ toYaml . | nindent 4 }}
  {{- end }}
spec:
  serviceName: {{ template "postgis.fullname" . }}-headless
  replicas: 1
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: {{ template "postgis.fullname" . }}
      release: {{ .Release.Name | quote }}
      role: master
  template:
    metadata:
      name: {{ template "postgis.fullname" . }}
      labels:
        app: {{ template "postgis.fullname" . }}
        chart: {{ template "postgis.chart" . }}
        release: {{ .Release.Name | quote }}
        heritage: {{ .Release.Service | quote }}
        role: master
        {{- with .Values.podLabels }}
        {{- tpl . $ | nindent 8 }}
        {{- end }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        checksum/secrets: {{ include (print $.Template.BasePath "/secrets.yaml") . | sha256sum }}
        {{- with .Values.podAnnotations }}
        {{- (tpl . $) | nindent 8 }}
        {{- end }}
    spec:
      securityContext:
      {{- with .Values.securityContext }}
      {{- tpl . $ | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ template "postgis.fullname" . }}
          image: {{ template "postgis.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if .Values.resources }}
          resources: {{- toYaml .Values.resources | nindent 12 }}
          {{- end }}
          env:
            {{- if .Values.postgresqlInitdbArgs }}
            - name: POSTGRES_INITDB_ARGS
              value: {{ .Values.postgresqlInitdbArgs | quote }}
            {{- end }}
            {{- if .Values.persistence.mountPath }}
            - name: PGDATA
              value: {{ .Values.postgresqlDataDir | quote }}
            {{- end }}
            - name: POSTGRES_USER
              value: {{ .Values.postgresqlUsername | quote }}
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ template "postgis.secretName" . }}
                  key: postgresql-password
            - name: POSTGRES_DBNAME
              value: {{ .Values.postgresqlDatabase | quote }}
            {{- if .Values.tls.enabled }}
            - name: SSL_CERT_FILE
              value: /cert/tls.crt
            - name: SSL_KEY_FILE
              value: /cert/tls.key
            - name: SSL_CA_FILE
              value: /cert/ca.crt
            {{- end }}
            {{- with .Values.extraPodEnv }}
            {{- tpl . $ | nindent 12 }}
            {{- end }}
          ports:
            - name: tcp-postgis
              containerPort: 5432
          volumeMounts:
            {{- if .Values.persistence.enabled }}
            - name: data
              mountPath: {{ .Values.persistence.mountPath }}
              subPath: {{ .Values.persistence.subPath }}
            {{- end }}
            {{- if .Values.tls.enabled }}
            - name: cert
              mountPath: /cert/tls.key
              subPath: {{ .Values.tls.key_file }}
              readOnly: true
            - name: cert
              mountPath: /cert/tls.crt
              subPath: {{ .Values.tls.cert_file }}
              readOnly: true
            - name: cert
              mountPath: /cert/ca.crt
              subPath: {{ .Values.tls.ca_file }}
              readOnly: true
            {{- end }}
            {{- with .Values.extraVolumeMounts }}
            {{- (tpl . $) | nindent 12 }}
            {{- end }}
          {{- if .Values.probe }}
            {{- with .Values.probe }}
            {{- tpl . $ | nindent 10 }}
            {{- end }}
          {{- else }}
          livenessProbe:
            exec:
              command:
                - bash
                - -c
                - "PGPASSWORD=$POSTGRES_PASSWORD pg_isready -h localhost -U $POSTGRES_USER -d {{ template "postgresql.firstDatabaseName" . }}"
            periodSeconds: 60
            successThreshold: 1
            failureThreshold: 3
            timeoutSeconds: 2
          startupProbe:
            exec:
              command:
                - bash
                - -c
                - "PGPASSWORD=$POSTGRES_PASSWORD pg_isready -h localhost -U $POSTGRES_USER -d {{ template "postgresql.firstDatabaseName" . }}"
            periodSeconds: 60
            successThreshold: 1
            failureThreshold: 5
            timeoutSeconds: 2
          readinessProbe:
            exec:
              command:
                - bash
                - -c
                - "PGPASSWORD=$POSTGRES_PASSWORD pg_isready -h localhost -U $POSTGRES_USER -d {{ template "postgresql.firstDatabaseName" . }}"
            periodSeconds: 5
            successThreshold: 1
            failureThreshold: 3
            timeoutSeconds: 2
          {{- end }}
      {{- with .Values.extraPodSpec }}
      {{- tpl . $ | nindent 6 }}
      {{- end }}
      volumes:
        {{- if .Values.tls.enabled }}
        - name: cert
          secret:
            secretName: {{ .Values.tls.secretName }}
            defaultMode: 0440
        {{- end }}
        {{- with .Values.extraVolume }}
        {{- (tpl . $) | nindent 8 }}
        {{- end }}
{{- if and .Values.persistence.enabled .Values.persistence.existingClaim }}
        - name: data
          persistentVolumeClaim:
{{- with .Values.persistence.existingClaim }}
            claimName: {{ tpl . $ }}
{{- end }}
{{- else if not .Values.persistence.enabled }}
        - name: data
          emptyDir: {}
{{- else if and .Values.persistence.enabled (not .Values.persistence.existingClaim) }}
  volumeClaimTemplates:
    - metadata:
        name: data
      {{- with .Values.persistence.annotations }}
        annotations:
        {{- range $key, $value := . }}
          {{ $key }}: {{ $value }}
        {{- end }}
      {{- end }}
      spec:
        accessModes:
        {{- range .Values.persistence.accessModes }}
          - {{ . | quote }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.persistence.size | quote }}
        {{ include "postgresql.storageClass" . }}
{{- end }}
