apiVersion: v2
name: geoserver-standalone

version: 0.2.1
appVersion: 2.24.2

description: Chart for GeoServer

keywords:
  - GeoServer
  - GIS

home: http://geoserver.org
sources:
  - https://github.com/geoserver/geoserver
maintainers:
  - name: tharanath-kartoza
    email: charts4kubernetes@gmail.com

dependencies:
- condition: postgis.enabled
  name: postgis
  repository: https://kartoza.github.io/charts
  tags:
  - geoserver-database
  version: 0.2.4

icon: https://raw.githubusercontent.com/kartoza/charts/master/assets/logo/GeoServer_500.png
