# Custom Dockerfile for kind node image that has open-iscsi installed
FROM kindest/node:v1.19.11@sha256:7664f21f9cb6ba2264437de0eb3fe99f201db7a3ac72329547ec4373ba5f5911
RUN apt -y update; apt -y install open-iscsi