{{- if or (not .Values.existingConfig) .Values.extraConfig }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "geoserver.configName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "geoserver.fullname" . }}
    chart: {{ template "geoserver.chart" . }}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
  {{- with .Values.labels }}
  {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.annotations }}
  annotations: {{ toYaml . | nindent 4 }}
  {{- end }}
data:
  {{- if not .Values.existingConfig }}
  httpHost: {{ .Values.httpHost | quote }}
  httpProxyName: {{ .Values.httpProxyName | quote }}
  communityExtensions: {{ .Values.communityExtensions | quote }}
  stableExtensions: {{ .Values.stableExtensions | quote }}
  initialMemory: {{ .Values.initialMemory | quote }}
  maximumMemory: {{ .Values.maximumMemory | quote }}
  csrfWhitelist: {{ .Values.csrfWhitelist | quote }}
  {{- end }}
  {{- with .Values.extraConfig }}
  {{- tpl . $ | nindent 2 }}
  {{- end }}
{{- end }}