{{- if (not (or .Values.postgis.enabled .Values.externalDatabase.existingSecret)) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-%s" .Release.Name "externaldb"  }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "geoserver.fullname" . }}
    chart: {{ template "geoserver.chart" . }}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
type: Opaque
data:
  database-user: {{ default "" .Values.externalDatabase.user | b64enc | quote }}
  database-db: {{ default "" .Values.externalDatabase.database | b64enc | quote }}
  database-port: {{ default "" .Values.externalDatabase.port | toString | b64enc | quote }}
  database-host: {{ default "" .Values.externalDatabase.host | b64enc | quote }}
  database-password: {{ default "" .Values.externalDatabase.password | b64enc | quote }}
  database-url: {{ default "" .Values.externalDatabase.url | b64enc | quote }}  
{{- end }}