{{- if or (not .Values.existingSecret) .Values.extraSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "geoserver.secretName" . }}
  labels:
    app: geoserver
    chart: {{ template "geoserver.chart" . }}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
type: Opaque
data:
  {{- if not .Values.existingSecret }}
  geoserver-password: {{ include "geoserver.password" . | b64enc | quote }}
  {{- end }}
  {{- with .Values.extraSecret }}
  {{- tpl . $ | nindent 2 }}
  {{- end }}
{{- end }}
