name: Release Charts

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Dereference README symlink
        run: |
          # Define the path to the dependency chart directory
          DEPENDENCY_CHART_DIR="charts/common"
          
          # Find the README symlink
          README_SYMLINK="${DEPENDENCY_CHART_DIR}/README.md"
          
          # Dereference the symlink
          # Replace the symlink with the actual README content
          cat "${README_SYMLINK}" > "${README_SYMLINK}.tmp" && mv "${README_SYMLINK}.tmp" "${README_SYMLINK}"
          
      - name: Run chart-releaser
        uses: lucernae/chart-releaser-action@rancher-1.0
        with:
          level: 3
          force: true
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
