apiVersion: v1
kind: Secret
metadata:
  name: {{ template "geonode.fullname" . }}
  labels:
    app: geonode
    chart: {{ template "geonode.chart" . }}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
type: Opaque
data:
  {{- if not .Values.global.djangoSecretKey.valueFrom.secretKeyRef.name }}
  django-secret: {{ include "geonode.secretValue" .Values.global.djangoSecretKey | b64enc | quote }}
  {{- end }}
  {{- if not .Values.global.geoserverAdminPassword.valueFrom.secretKeyRef.name }}
  geoserver-password: {{ include "geonode.secretValue" .Values.global.geoserverAdminPassword | b64enc | quote }}
  {{- end }}
  {{- if not .Values.global.geodatabasePassword.valueFrom.secretKeyRef.name }}
  geodatabase-password: {{ include "geonode.secretValue" .Values.global.geodatabasePassword | b64enc | quote }}
  {{- end }}
  {{- if not .Values.global.databasePassword.valueFrom.secretKeyRef.name }}
  database-password: {{ include "geonode.secretValue" .Values.global.databasePassword | b64enc | quote }}
  {{- end }}
  {{- if not .Values.global.adminPassword.valueFrom.secretKeyRef.name }}
  admin-password: {{ include "geonode.secretValue" .Values.global.adminPassword | b64enc | quote }}
  {{- end }}
