apiVersion: v1
kind: Secret
metadata:
  name: {{ template "geonode.sharedSecretName" . }}
  labels:
    app: geonode
    chart: {{ template "geonode.chart" . }}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
type: Opaque
data:
{{- if not .Values.global.existingSecret -}}
  {{- if not .Values.global.djangoSecretKey.valueFrom.secretKeyRef.name }}
  {{ .Values.global.djangoSecretKey.valueFrom.secretKeyRef.key }}: {{ include "geonode.secretValue" .Values.global.djangoSecretKey | b64enc | quote }}
  {{- end }}
  {{- if not .Values.global.geoserverAdminPassword.valueFrom.secretKeyRef.name }}
  {{ .Values.global.geoserverAdminPassword.valueFrom.secretKeyRef.key }}: {{ include "geonode.secretValue" .Values.global.geoserverAdminPassword | b64enc | quote }}
  {{- end }}
  {{- if not .Values.global.geodatabasePassword.valueFrom.secretKeyRef.name }}
  {{- $geodatabasePassword := include "geonode.secretValue" .Values.global.geodatabasePassword }}
  {{ .Values.global.geodatabasePassword.valueFrom.secretKeyRef.key }}: {{ $geodatabasePassword | b64enc | quote }}
  geodatabase-url: {{ printf "postgis://%s:%s@%s:%d/%s" .Values.global.geodatabaseUsername $geodatabasePassword (include "geonode.geodatabaseHost" .) (int .Values.global.geodatabasePort) .Values.global.geodatabaseName | b64enc | quote }}
  {{- end }}
  {{- if not .Values.global.databasePassword.valueFrom.secretKeyRef.name }}
  {{- $databasePassword := include "geonode.secretValue" .Values.global.databasePassword }}
  {{ .Values.global.databasePassword.valueFrom.secretKeyRef.key }}: {{ $databasePassword | b64enc | quote }}
  postgresql-password: {{ $databasePassword | b64enc | quote }}
  database-url: {{ printf "postgres://%s:%s@%s:%d/%s" .Values.global.databaseUsername $databasePassword (include "geonode.databaseHost" .) (int .Values.global.databasePort) .Values.global.databaseName | b64enc | quote }}
  {{- end }}
  {{- if not .Values.global.adminPassword.valueFrom.secretKeyRef.name }}
  {{ .Values.global.adminPassword.valueFrom.secretKeyRef.key }}: {{ include "geonode.secretValue" .Values.global.adminPassword | b64enc | quote }}
  {{- end }}
{{- end -}}
