apiVersion: v1
kind: Service
metadata:
  name: {{ template "geonode.fullname" . }}
  labels:
    app: geonode
    chart: {{ template "geonode.fullname" . }}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
    kubernetes.io/cluster-service: "true"
spec:
  type: ClusterIP
  clusterIP: ""
  {{- if .Values.service.externalIPs }}
  externalIPs: {{ .Values.service.externalIPs }}
  {{- end }}
  ports:
    - name: http-geonode
      port: 80
      protocol: TCP
      targetPort: nginx-geonode
  selector:
    app: geonode
    release: {{ .Release.Name | quote }}
